// Generated for: Unity.NodeApi 0.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.9.0.0
/* eslint-disable */

import './mscorlib';


export class DOMRect extends ValueType {
	x: number;

	y: number;

	width: number;

	height: number;

	readonly left: number;

	readonly top: number;

	readonly right: number;

	readonly bottom: number;
}

export class Event {
	readonly type: string;

	readonly timestamp: number;

	readonly target: Object;

	readonly currentTarget: Object;

	readonly bubbles: boolean;

	readonly isPropagationStopped: boolean;

	toString(): string;

	dispose(): void;

	stopPropagation(): void;

	stopImmediatePropagation(): void;
}

export interface Loader { (path: string): Promise<Object>; }

export class Node {
	readonly ptr: Object;

	static readonly event?: Event;

	static loadAssetAsync: Loader;

	static isPropTypeSupported<T>(): boolean;

	dispose(): void;

	equals(other: Object | undefined): boolean;

	getHashCode(): number;

	toString(): string;

	setProps(props: any): void;

	setActive(value: boolean): void;

	setParent(
		parent: Node | undefined,
		beforeChild?: Node,
	): void;

	clear(): void;

	getBoundingClientRect(): DOMRect | undefined;

	static create(kind: Object): Node | undefined;

	static search(
		name: Object,
		scope?: Node,
	): Node | undefined;
}
