// Generated for: Unity.NodeApi 0.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.9.0.0
/* eslint-disable */

import './mscorlib';


export class DOMRect extends ValueType {
	x: number;

	y: number;

	width: number;

	height: number;

	readonly left: number;

	readonly top: number;

	readonly right: number;

	readonly bottom: number;
}

export interface Loader { (path: string): Promise<Object>; }

export class Node {
	readonly ptr: Object;

	static loadAssetAsync: Loader;

	static isPropTypeSupported<T>(): boolean;

	dispose(): void;

	equals(other: Object): boolean;

	getHashCode(): number;

	toString(): string;

	setProps(props: any): void;

	setActive(value: boolean): void;

	setParent(
		parent: Node,
		beforeChild?: Node,
	): void;

	clear(): void;

	getBoundingClientRect(): DOMRect;

	static create(kind: Object): Node;

	static search(
		name: Object,
		scope?: Node,
	): Node;
}
