// Generated for: Unity.NodeApi 0.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.9.0.0
/* eslint-disable */

const browser = (typeof window !== 'undefined');
const exports = (await import(browser ? './index-web.js' : './index-node.js')).default;
export default exports;

export const {
	createObject,
	deleteObject,
	appendChildObject,
	insertBeforeObject,
	removeChildObject,
	setObjectProperty,
	hideObject,
	unhideObject,
	clearObject,
	activeScene,
} = exports;
