// Generated for: Unity.NodeApi 0.0.0.0
// Generated by: Microsoft.JavaScript.NodeApi.Generator 0.9.0.0
/* eslint-disable */

const suffix = (typeof window !== 'undefined') ? 'web' : 'node';
const { default: exports } = await import(`./index-${suffix}.js`);
export default exports;

export const {
	DOMRect,
	Event,
	Loader,
	Node,
	RoutedEvent,
	ChangeEvent,
	PointerEvent,
} = exports;
